const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const defaultAgents=[
 {id:'study',name:'Study Agent',icon:'🎓',desc:'Explains concepts clearly and helps you prepare for exams.',status:'online',tags:['Explain','Teach','Quiz'],system:'You are a patient study assistant. Explain concepts in simple language, use examples, and structure answers for a college student. If asked for code, keep it readable.'},
 {id:'document',name:'Document Agent',icon:'📄',desc:'Reads documents and turns them into useful notes.',status:'online',tags:['Summarize','Q&A','Notes'],system:'You are a document analysis assistant. Answer from the supplied document context when available. Be concise, accurate, and say when the document does not contain enough information.'},
 {id:'coding',name:'Coding Agent',icon:'💻',desc:'Helps write, understand and debug practical code.',status:'online',tags:['Code','Debug','Review'],system:'You are a beginner-friendly coding mentor. Explain code step by step, identify bugs clearly, and provide simple working examples.'},
 {id:'research',name:'Research Agent',icon:'🔎',desc:'Turns questions into structured research answers.',status:'idle',tags:['Research','Compare','Ideas'],system:'You are a research assistant. Give balanced, structured answers, distinguish facts from assumptions, and suggest useful next steps.'}
];
const state={agents:JSON.parse(localStorage.getItem('af_agents')||'null')||defaultAgents,tasks:JSON.parse(localStorage.getItem('af_tasks')||'null')||[
 {id:1,title:'Prepare DAA revision notes',agent:'Study Agent',priority:'High',status:'running',detail:'Explain divide and conquer algorithms'},
 {id:2,title:'Review JavaScript assignment',agent:'Coding Agent',priority:'Medium',status:'pending',detail:'Check functions and event handling'},
 {id:3,title:'Analyze sample PDF',agent:'Document Agent',priority:'Low',status:'completed',detail:'Extract important sections'}
],docs:JSON.parse(localStorage.getItem('af_docs')||'[]'),activity:JSON.parse(localStorage.getItem('af_activity')||'null')||[],selectedAgent:'study',chats:JSON.parse(localStorage.getItem('af_chats')||'{}')};
function save(){localStorage.setItem('af_agents',JSON.stringify(state.agents));localStorage.setItem('af_tasks',JSON.stringify(state.tasks));localStorage.setItem('af_docs',JSON.stringify(state.docs));localStorage.setItem('af_activity',JSON.stringify(state.activity));localStorage.setItem('af_chats',JSON.stringify(state.chats));}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg,type='success'){const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=msg;$('#toastWrap').append(el);setTimeout(()=>el.remove(),2800)}
function log(type,message){state.activity.unshift({id:Date.now(),type,message,time:new Date().toISOString()});state.activity=state.activity.slice(0,100);save();renderActivity();renderDashboard()}
function agentById(id){return state.agents.find(a=>a.id===id)||state.agents[0]}
function renderDashboard(){
 $('#statAgents').textContent=state.agents.length;$('#statTasks').textContent=state.tasks.length+9;$('#statCompleted').textContent=state.tasks.filter(t=>t.status==='completed').length+8;$('#statDocs').textContent=state.docs.length;
 $('#agentHealth').innerHTML=state.agents.map(a=>`<div class="agent-row"><span class="agent-icon">${a.icon}</span><div><strong>${esc(a.name)}</strong><small>${esc(a.desc)}</small></div><span class="status ${a.status}">${a.status}</span></div>`).join('');
 $('#recentActivity').innerHTML=(state.activity.length?state.activity: [{type:'system',message:'Workspace ready',time:new Date().toISOString()}]).slice(0,5).map(a=>`<div class="activity-item"><i class="dot"></i><div><strong>${esc(a.message)}</strong><small>${new Date(a.time).toLocaleString()}</small></div></div>`).join('');
 $('#taskBadge').textContent=state.tasks.filter(t=>t.status==='pending'||t.status==='running').length;
}
function renderAgents(){ $('#agentCards').innerHTML=state.agents.map(a=>`<div class="agent-card panel"><div class="agent-card-top"><span class="agent-icon">${a.icon}</span><div><h2>${esc(a.name)}</h2><span class="status ${a.status}">${a.status}</span></div></div><p>${esc(a.desc)}</p><div>${a.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join(' ')}</div><div class="agent-card-actions"><button class="secondary" onclick="selectAgent('${a.id}')">Open chat</button><button class="secondary" onclick="toggleAgent('${a.id}')">${a.status==='online'?'Set idle':'Set online'}</button></div></div>`).join('') }
function renderTasks(){const q=($('#taskSearch')?.value||'').toLowerCase(),f=$('#taskFilter')?.value||'all';const rows=state.tasks.filter(t=>(f==='all'||t.status===f)&&(`${t.title} ${t.agent}`.toLowerCase().includes(q)));$('#taskRows').innerHTML=rows.length?rows.map(t=>`<div class="task-row"><div><strong>${esc(t.title)}</strong><small>${esc(t.detail||'')}</small></div><span>${esc(t.agent)}</span><span class="priority ${t.priority.toLowerCase()}">${t.priority}</span><span class="task-status ${t.status}">${t.status}</span><button class="row-action" onclick="cycleTask(${t.id})">${t.status==='completed'?'↻ Restart':'Run'}</button></div>`).join(''):`<div class="empty">No tasks found.</div>`}
function renderDocs(){ $('#documentGrid').innerHTML=state.docs.length?state.docs.map(d=>`<div class="document-card panel"><h3>📄 ${esc(d.name)}</h3><p>${d.size} · ${new Date(d.time).toLocaleString()}</p><div class="doc-actions"><button onclick="analyzeDoc('${d.id}','summary')">Summarize</button><button onclick="analyzeDoc('${d.id}','questions')">Ask questions</button><button onclick="analyzeDoc('${d.id}','mcq')">Generate MCQs</button><button onclick="analyzeDoc('${d.id}','keypoints')">Key points</button></div></div>`).join(''):`<div class="panel" style="grid-column:1/-1;text-align:center;color:var(--muted);font-size:10px;padding:28px">No documents yet. Upload a PDF to start.</div>` }
function renderActivity(){const q=($('#activitySearch')?.value||'').toLowerCase(),f=$('#activityFilter')?.value||'all';$('#activityFull').innerHTML=state.activity.filter(a=>(f==='all'||a.type===f)&&a.message.toLowerCase().includes(q)).map(a=>`<div class="activity-full-row"><time>${new Date(a.time).toLocaleTimeString()}</time><span class="event-type">${a.type}</span><strong>${esc(a.message)}</strong><span>${new Date(a.time).toLocaleDateString()}</span></div>`).join('')||'<div class="empty" style="padding:30px;text-align:center">No matching activity.</div>'}
function renderChat(){const a=agentById(state.selectedAgent);$('#chatAgents').innerHTML=state.agents.map(x=>`<button class="chat-agent ${x.id===a.id?'active':''}" onclick="selectAgent('${x.id}')"><span class="agent-icon">${x.icon}</span><span><strong>${esc(x.name)}</strong><small>${esc(x.desc)}</small></span></button>`).join('');$('#chatAgentIcon').textContent=a.icon;$('#chatAgentName').textContent=a.name;$('#chatAgentDesc').textContent=a.desc;const msgs=state.chats[a.id]||[];$('#messages').innerHTML=msgs.length?msgs.map(m=>`<div class="message ${m.role==='user'?'user':'ai'}"><div class="bubble">${esc(m.content)}</div><div class="message-meta">${m.role==='user'?'You':a.name} · ${new Date(m.time).toLocaleTimeString()}</div></div>`).join(''):`<div class="empty" style="text-align:center;padding:80px 20px;color:var(--muted);font-size:10px">Start a conversation with <b>${esc(a.name)}</b>.<br>Try one of the suggestions below.</div>`;$('#messages').scrollTop=$('#messages').scrollHeight}
function nav(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id===view));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const titles={dashboard:['Dashboard','Your AI workspace at a glance'],chat:['AI Chat','Talk to your selected agent'],agents:['Agents','Manage your AI workforce'],tasks:['Task Queue','Create and track work'],documents:['Documents','Analyze PDFs with AI'],activity:['Activity Log','Everything your agents have done'],settings:['Settings','Workspace preferences']};$('#pageTitle').textContent=titles[view][0];$('#pageSubtitle').textContent=titles[view][1];window.scrollTo({top:0,behavior:'smooth'});if(view==='chat')renderChat();if(view==='agents')renderAgents();if(view==='tasks')renderTasks();if(view==='documents')renderDocs();if(view==='activity')renderActivity();$('#sidebar').classList.remove('open')}
function selectAgent(id){state.selectedAgent=id;nav('chat')}
function toggleAgent(id){const a=agentById(id);a.status=a.status==='online'?'idle':'online';save();renderAgents();renderDashboard();log('system',`${a.name} is now ${a.status}`)}
function cycleTask(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;if(t.status==='pending')t.status='running';else if(t.status==='running')t.status='completed';else t.status='running';save();renderTasks();renderDashboard();log('task',`${t.title} → ${t.status}`);toast(`Task ${t.status}`)}
function openModal(html){$('#modal').innerHTML=html;$('#modalBackdrop').classList.add('open')}
function closeModal(){$('#modalBackdrop').classList.remove('open')}
async function sendChat(text){const input=$('#chatInput');text=(text||input.value).trim();if(!text)return;input.value='';const a=agentById(state.selectedAgent);state.chats[a.id]??=[];state.chats[a.id].push({role:'user',content:text,time:Date.now()});renderChat();log('chat',`${a.name} received: ${text.slice(0,70)}`);const typing={role:'ai',content:'Thinking…',time:Date.now(),typing:true};state.chats[a.id].push(typing);renderChat();try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({agent:a,input:state.chats[a.id].filter(m=>!m.typing).map(m=>({role:m.role,content:m.content})),model:localStorage.getItem('af_model')||'gpt-6-luna'})});const data=await r.json();state.chats[a.id]=state.chats[a.id].filter(m=>!m.typing);state.chats[a.id].push({role:'ai',content:data.reply||data.error||'No response received.',time:Date.now()});save();renderChat();log('chat',`${a.name} completed a response`);if(data.demo)toast('Demo response — add OPENAI_API_KEY for live AI','error')}catch(e){state.chats[a.id]=state.chats[a.id].filter(m=>!m.typing);state.chats[a.id].push({role:'ai',content:'The server is not running. Start it with `npm install` and `npm start` from the project folder.',time:Date.now()});save();renderChat();toast('Backend unavailable','error')}}
async function analyzeDoc(id,mode){const d=state.docs.find(x=>x.id===id);if(!d)return;openModal(`<h2>Analyzing ${esc(d.name)}</h2><p>AgentFlow is sending the document to the document agent. This may take a moment.</p><div class="connection-box"><i></i><div><strong>Processing ${mode}</strong><small>Please keep this tab open.</small></div></div>`);try{const r=await fetch('/api/document-action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({documentId:id,mode})});const data=await r.json();closeModal();openModal(`<h2>${mode==='summary'?'Summary':mode==='questions'?'Questions':mode==='mcq'?'MCQs':'Key points'}</h2><div style="max-height:55vh;overflow:auto;white-space:pre-wrap;font-size:10px;line-height:1.7;margin-top:14px">${esc(data.result||data.error||'No result')}</div><div class="modal-actions"><button class="primary" onclick="closeModal()">Done</button></div>`);log('document',`${d.name}: ${mode} generated`);if(data.demo)toast('Demo document response — add API key for live AI','error')}catch(e){closeModal();toast('Could not process document','error')}}
async function uploadPdf(file){if(!file||file.type!=='application/pdf'){toast('Please choose a PDF file','error');return}if(file.size>10*1024*1024){toast('PDF must be under 10 MB','error');return}const fd=new FormData();fd.append('pdf',file);toast('Uploading PDF…');try{const r=await fetch('/api/upload', {method:'POST',body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error);state.docs.unshift({id:d.id,name:file.name,size:(file.size/1024/1024).toFixed(2)+' MB',time:Date.now()});save();renderDocs();log('document',`Uploaded ${file.name}`);toast('PDF uploaded successfully')}catch(e){toast(e.message||'Upload failed','error')}}
function init(){
 $$('[data-view]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.view)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.go)));
 $('#chatForm').addEventListener('submit',e=>{e.preventDefault();sendChat()});$('#chatInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendChat()}});$('#newChatBtn').onclick=()=>{state.chats[state.selectedAgent]=[];save();renderChat();toast('New chat started')};$$('.suggestions button').forEach(b=>b.onclick=()=>sendChat(b.textContent));
 $('#addTaskBtn').onclick=()=>openModal(`<h2>Create a task</h2><p>Tasks are stored locally and can be progressed through the queue.</p><label>Task title</label><input id="mTask" placeholder="e.g. Summarize lecture notes"><label>Agent</label><select id="mAgent">${state.agents.map(a=>`<option>${esc(a.name)}</option>`).join('')}</select><label>Priority</label><select id="mPriority"><option>High</option><option selected>Medium</option><option>Low</option></select><div class="modal-actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" onclick="createTask()">Create task</button></div>`);
 $('#addAgentBtn').onclick=()=>openModal(`<h2>Create an agent</h2><p>Give your agent a focused job.</p><label>Name</label><input id="mName" placeholder="e.g. Presentation Agent"><label>Description</label><input id="mDesc" placeholder="Creates polished presentation outlines"><label>Icon</label><input id="mIcon" value="✨"><div class="modal-actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" onclick="createAgent()">Create agent</button></div>`);
 $('#choosePdf').onclick=()=>$('#pdfInput').click();$('#pdfInput').onchange=e=>uploadPdf(e.target.files[0]);const dz=$('#dropZone');['dragenter','dragover'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>uploadPdf(e.dataTransfer.files[0]));
 $('#taskSearch').oninput=renderTasks;$('#taskFilter').onchange=renderTasks;$('#activitySearch').oninput=renderActivity;$('#activityFilter').onchange=renderActivity;$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('af_dark',document.body.classList.contains('dark'))};if(localStorage.getItem('af_dark')==='true')document.body.classList.add('dark');$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');$('#modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()};$('#clearDataBtn').onclick=()=>{if(confirm('Reset all local AgentFlow data?')){localStorage.clear();location.reload()}};
 $('#saveHistory').onchange=e=>localStorage.setItem('af_save',e.target.checked);$('#compactMode').onchange=e=>document.body.classList.toggle('compact',e.target.checked);$('#modelSelect').onchange=e=>localStorage.setItem('af_model',e.target.value);$('#exportActivity').onclick=()=>{const blob=new Blob([JSON.stringify(state.activity,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='agentflow-activity.json';a.click();URL.revokeObjectURL(a.href)};
 renderDashboard();renderAgents();renderTasks();renderDocs();renderActivity();renderChat();checkServer();
}
async function checkServer(){try{const r=await fetch('/api/health');const d=await r.json();const live=d.aiConfigured;$('#apiDot').style.background=live?'#20b486':'#e5a22c';$('#apiStatus').textContent=live?'Live AI':'Demo mode';$('#apiStatusText').textContent=live?'OpenAI connected':'Add API key for live AI';$('#settingsDot').style.background=live?'#20b486':'#e5a22c';$('#settingsStatus').textContent=live?'Live AI connected':'Demo mode — backend ready'}catch(e){$('#apiStatus').textContent='Backend offline';$('#apiStatusText').textContent='Start npm server';$('#settingsStatus').textContent='Backend offline'}}
window.selectAgent=selectAgent;window.toggleAgent=toggleAgent;window.cycleTask=cycleTask;window.closeModal=closeModal;window.analyzeDoc=analyzeDoc;
window.createTask=()=>{const title=$('#mTask').value.trim();if(!title)return toast('Enter a task title','error');state.tasks.unshift({id:Date.now(),title,agent:$('#mAgent').value,priority:$('#mPriority').value,status:'pending',detail:'Created from AgentFlow'});save();closeModal();renderTasks();renderDashboard();log('task',`Created task: ${title}`);toast('Task created')};
window.createAgent=()=>{const name=$('#mName').value.trim();if(!name)return toast('Enter an agent name','error');const id=name.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'-'+Date.now();state.agents.push({id,name,icon:$('#mIcon').value||'✨',desc:$('#mDesc').value||'Custom AI agent',status:'online',tags:['Custom'],system:'You are a helpful custom AI agent. Be clear, useful and practical.'});save();closeModal();renderAgents();renderDashboard();toast('Agent created');log('system',`Created ${name}`)};
document.addEventListener('DOMContentLoaded',init);
